Loading checkpoint shards: 100%|██████████████████| 8/8 [00:16<00:00,  2.03s/it]
INFO:__main__:Tokenizer max length: 1000000000000000019884624838656
INFO:__main__:Loading datasets...
INFO:__main__:Train dataset length: 7473
INFO:__main__:Validation dataset length: 1319
Traceback (most recent call last):
  File "/home/llm4math/LLM-for-Math/Direct Verifier/code/train.py", line 82, in <module>
    main(args)
  File "/home/llm4math/LLM-for-Math/Direct Verifier/code/train.py", line 48, in main
    trainable, total = model.get_nb_trainable_parameters()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'Gemma2ForCausalLM' object has no attribute 'get_nb_trainable_parameters'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/llm4math/LLM-for-Math/Direct Verifier/code/train.py", line 82, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/llm4math/LLM-for-Math/Direct Verifier/code/train.py", line 48, in main
[rank0]:     trainable, total = model.get_nb_trainable_parameters()
[rank0]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/llm4math/miniconda3/envs/mathllm/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank0]:     raise AttributeError(
[rank0]: AttributeError: 'Gemma2ForCausalLM' object has no attribute 'get_nb_trainable_parameters'
